### ISSUE TITLE
Critical messages don't overcome silence settings on Android

### ISSUE THREAD

**Issue by energywave** [energywave/multinotify#2]
With the new version changed in 2022.8 (that was implemented in multinotify) critical notifications on Android companion app seems not to play sound when phone is silenced.

**Comment by mcv93us** [comment]
I think it's due to the changes made to the companion APP as well, as I reported to you here some time ago: https://github.com/energywave/homeassistant-packages/issues/2
However I see that they have already proposed a fix.

**Comment by energywave** [comment]
> I think it's due to the changes made to the companion APP as well, as I reported to you here some time ago: [energywave/homeassistant-packages#2](https://github.com/energywave/homeassistant-packages/issues/2) However I see that they have already proposed a fix.

No, I already implemented new syntax of Android app version >= 2022.8. It was due to the fact that the channel was sent to `None` when set `critical: true` and that's now wrong.
As I stated in the updated 3.7.0 readme and changelog you have to set a `channel` and `critical:true`. If it's the first notification with that channel the app create the channel with appropriate parameters (ex: to bypass *Do Not Disturb* mode).
If you send a notification to an already created channel that was created without `critical: true` then you have to set channel settings by hand in Android settings.
That's how the Companion app on Android works, I tried to explain and to implement at best.

**Resolved in ver 3.7.0**
