### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by alexcroce** [energywave/multinotify#4]
Hello. i'm trying to test the service. When i try in services for developers, it works fine, but i receive this in settings:

![image](https://user-images.githubusercontent.com/54688054/213288788-e48951ba-f1b8-4809-b1a7-1b3e3f1948ac.png)

Can you help to solve it?

**Comment by energywave** [comment]
Hello, you did not install the needed service [saver](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver). Please read carefully the [Dependencies](https://github.com/energywave/multinotify#dependencies) section of the readme and install the [saver](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver) service.

**Comment by alexcroce** [comment]
Thanks, i installed it but not wrote in configuration.yaml "saver:" in order to activate it.
